### ISSUE TITLE
Installed android apk flash back on andriod phone

### ISSUE THREAD

**Issue by PPGGG** [k2-fsa/sherpa-ncnn#216]
I tried to run the apk on my andriod phone, but it just flash back. I even tried to run it on a simulator phone on Android Studio, but it also can not work successfully.

**Comment by PPGGG** [comment]
> 

I generated the apk following the document https://k2-fsa.github.io/sherpa/ncnn/android/build-sherpa-ncnn.html#download-sherpa-ncnn.
The log is below:

```
---------------------------- PROCESS STARTED (6623) for package com.k2fsa.sherpa.ncnn ----------------------------
2023-05-25 11:05:52.055  6623-6642  ActivityThread          com.k2fsa.sherpa.ncnn                I  Init compatible state: true
2023-05-25 11:05:52.055  6623-6642  HwFramewor...rtsFactory com.k2fsa.sherpa.ncnn                D  HwFrameworkSecurityPartsFactory in.
2023-05-25 11:05:52.056  6623-6642  HwFramewor...rtsFactory com.k2fsa.sherpa.ncnn                I  add HwFrameworkSecurityPartsFactory to memory.
2023-05-25 11:05:52.056  6623-6642  BehaviorCollectManager  com.k2fsa.sherpa.ncnn                D  hook process for AI virus second
2023-05-25 11:05:52.060  6623-6642  BehaviorCollectManager  com.k2fsa.sherpa.ncnn                I  bindAnalyzerService: huawei.android.security.IAppBehaviorDataAnalyzer$Stub$Proxy@a889c9b pid:6623
2023-05-25 11:05:52.064  6623-6623  ApplicationLoaders      com.k2fsa.sherpa.ncnn                D  createClassLoader zip: /data/app/com.k2fsa.sherpa.ncnn-l8lt1eZBsIvBP3g3tEInbQ==/base.apk librarySearchPath: /data/app/com.k2fsa.sherpa.ncnn-l8lt1eZBsIvBP3g3tEInbQ==/lib/arm64:/data/app/com.k2fsa.sherpa.ncnn-l8lt1eZBsIvBP3g3tEInbQ==/base.apk!/lib/arm64-v8a libraryPermittedPath: /data/user/0/com.k2fsa.sherpa.ncnn parent: java.lang.BootClassLoader@67c1bc4 targetSdkVersion: 32 isBundled: false classLoaderName: null sharedLibraries: null
2023-05-25 11:05:52.210  6623-6623  fsa.sherpa.ncn          com.k2fsa.sherpa.ncnn                I  HwMultiThreadDexLoader location /data/app/com.k2fsa.sherpa.ncnn-l8lt1eZBsIvBP3g3tEInbQ==/base.apk start threadNum=2
2023-05-25 11:05:52.224  6623-6642  HwApiCacheMangerEx      com.k2fsa.sherpa.ncnn                I  apicache path=/storage/emulated/0 state=mounted key=com.k2fsa.sherpa.ncnn#10489#256
2023-05-25 11:05:52.224  6623-6642  HwApiCacheMangerEx      com.k2fsa.sherpa.ncnn                I  need clear apicache,because volumes changed,oldCnt=0 newCnt=1
2023-05-25 11:05:52.225  6623-6642  HwApiCacheMangerEx      com.k2fsa.sherpa.ncnn                I  apicache path=/storage/emulated/0 state=mounted key=com.k2fsa.sherpa.ncnn#10489#0
2023-05-25 11:05:52.225  6623-6642  HwApiCacheMangerEx      com.k2fsa.sherpa.ncnn                I  need clear apicache,because volumes changed,oldCnt=1 newCnt=1
2023-05-25 11:05:52.229  6623-6642  AwareBitmapCacher       com.k2fsa.sherpa.ncnn                I  init processName:com.k2fsa.sherpa.ncnn pid=6623 uid=10489
2023-05-25 11:05:52.229  6623-6660  AwareLog                com.k2fsa.sherpa.ncnn                E  AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@44bb576
2023-05-25 11:05:52.233  6623-6623  HwTypeface              com.k2fsa.sherpa.ncnn                I  updateFont: scale=1.0
2023-05-25 11:05:52.233  6623-6623  SystemFonts             com.k2fsa.sherpa.ncnn                D  areFontsVariable: script=Hans
2023-05-25 11:05:52.234  6623-6623  ActivityThread          com.k2fsa.sherpa.ncnn                I  finishPreloaded preloadStatus 0
2023-05-25 11:05:52.234  6623-6623  RmeSchedManager         com.k2fsa.sherpa.ncnn                I  init Rme, version is: v1.0
2023-05-25 11:05:52.234  6623-6623  RtgSchedEvent           com.k2fsa.sherpa.ncnn                I  current pid:6623 AppType:-1
2023-05-25 11:05:52.234  6623-6623  RmeSchedManager         com.k2fsa.sherpa.ncnn                I  init Rme, version is: v1.0
2023-05-25 11:05:52.237  6623-6623  OpenGLRenderer          com.k2fsa.sherpa.ncnn                D  disableOutlineDraw is true
2023-05-25 11:05:52.239  6623-6663  OpenGLRenderer          com.k2fsa.sherpa.ncnn                I  RenderThread: progress name = [com.k2fsa.sherpa.ncnn], viewCornerType = 0
2023-05-25 11:05:52.239  6623-6665  iGraphics               com.k2fsa.sherpa.ncnn                I  [0020080c] pn: com.k2fsa.sherpa.ncnn, p: 6623
2023-05-25 11:05:52.239  6623-6665  iGraphics               com.k2fsa.sherpa.ncnn                I  [0030080c] no spt app: com.k2fsa.sherpa.ncnn
2023-05-25 11:05:52.267  6623-6623  ActivityThread          com.k2fsa.sherpa.ncnn                V  callActivityOnCreate
2023-05-25 11:05:52.282  6623-6623  DecorView[]             com.k2fsa.sherpa.ncnn                I  pkgName:com.k2fsa.sherpa.ncnn old windowMode:0 new windoMode:1, isFixedSize:false
2023-05-25 11:05:52.295  6623-6623  OverScroll...timization com.k2fsa.sherpa.ncnn                I  start init SmartSlideOverScroller and get the overscroller config
2023-05-25 11:05:52.295  6623-6623  OverScroll...timization com.k2fsa.sherpa.ncnn                I  get the overscroller config
2023-05-25 11:05:52.316  6623-6623  fsa.sherpa.ncn          com.k2fsa.sherpa.ncnn                W  Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
2023-05-25 11:05:52.317  6623-6623  fsa.sherpa.ncn          com.k2fsa.sherpa.ncnn                W  Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2023-05-25 11:05:52.370  6623-6623  sherpa-ncnn             com.k2fsa.sherpa.ncnn                I  Start to initialize model
2023-05-25 11:05:52.374  6623-6623  ncnn                    com.k2fsa.sherpa.ncnn                W  ------config------
                                                                                                    RecognizerConfig(feat_config=FeatureExtractorConfig(sampling_rate=16000, feature_dim=80), model_config=ModelConfig(encoder_param="streaming_models/encoder.param", encoder_bin="streaming_models/encoder.bin", decoder_param="streaming_models/decoder.param", decoder_bin="streaming_models/decoder.bin", joiner_param="streaming_models/joiner.param", joiner_bin="streaming_models/joiner.bin", tokens="streaming_models/tokens.txt", encoder num_threads=1, decoder num_threads=1, joiner num_threads=1), decoder_config=DecoderConfig(method="greedy_search", num_active_paths=4), endpoint_config=EndpointConfig(rule1=EndpointRule(must_contain_nonsilence=False, min_trailing_silence=2, min_utterance_length=0), rule2=EndpointRule(must_contain_nonsilence=True, min_trailing_silence=0.8, min_utterance_length=0), rule3=EndpointRule(must_contain_nonsilence=False, min_trailing_silence=0, min_utterance_length=20)), enable_endpoint=True)
2023-05-25 11:05:52.461  6623-6623  ncnn                    com.k2fsa.sherpa.ncnn                W  You are using a too old version of Zipformer. You can choose one of the following solutions: 
                                                                                                      (1) Re-download the latest model
                                                                                                      (2) Re-export your model using the latest icefall. Remember to strictly follow the documentation
                                                                                                          to update the version number to 1.
                                                                                                      (3) Use sherpa-ncnn < v2.0 (not recommended)
```

**Comment by PPGGG** [comment]
It seems that the problem came from the model initialization. I will try to debug it.

**Comment by csukuangfj** [comment]
Please redownload the model.

**Comment by csukuangfj** [comment]
Or re-export the model by following the latest icefall doc with the latest icefall.

**Comment by PPGGG** [comment]
> Or re-export the model by following the latest icefall doc with the latest icefall.

What i used is the smallest Chinese model. https://k2-fsa.github.io/sherpa/ncnn/pretrained_models/zipformer-transucer-models.html#marcoyang-sherpa-ncnn-streaming-zipformer-zh-14m-2023-02-23-chinese

**Comment by csukuangfj** [comment]
When did you download it? If not this week, please redownload it.

**Comment by PPGGG** [comment]
> When did you download it? If not this week, please redownload it.

Now it's okay. However, i also tried to export the model using `https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/export-for-ncnn-zh.py`. I still get the same error.

**Comment by csukuangfj** [comment]
Are you following the latest icefall doc to export the model?

If not, please do it now. You need to add a version field to the exported encoder. We have documented it clearly.

**Comment by PPGGG** [comment]
> Are you following the latest icefall doc to export the model?
> 
> If not, please do it now. You need to add a version field to the exported encoder. We have documented it clearly.

Thanks @csukuangfj . I have tried to export the trained model to sherpa ncnn model following the latest icefall. However, the decode output is empty. 

Then i tried to decode the audio using the original checkpoint. To my surprised, the model can get a correct result.

**Comment by csukuangfj** [comment]
Are you using int8?

**Comment by PPGGG** [comment]
> Are you using int8?

Yes. I am using int8.

**Comment by PPGGG** [comment]
> Are you using int8?

Do i need to train the model from scratch using the latest icefall code ?

**Comment by csukuangfj** [comment]
Can you try a non-quantized model?

**Comment by PPGGG** [comment]
> Can you try a non-quantized model?

Yes. The checkpoint i used is a non-quantized model. I used `icefall/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/pretrained.py`

**Comment by csukuangfj** [comment]
I mean, could you try to use a non-quantized model for sherpa-ncnn? That is, replace encoder-xxx.int8.param with encoder-xxx.param

**Comment by PPGGG** [comment]
> > I mean, could you try to use a non-quantized model for sherpa-ncnn? That is, replace encoder-xxx.int8.param with encoder-xxx.param
> 
> I tried to use `pnnx joiner_jit_trace-pnnx.pt fp16=0` for `encoder, decoder and joiner`, still got the error :
> 
> ```
> File "pruned_transducer_stateless7_streaming/streaming-ncnn-decode.py", line 446, in <module>
>     main()
>   File "pruned_transducer_stateless7_streaming/streaming-ncnn-decode.py", line 378, in main
>     model = Model(args)
>   File "pruned_transducer_stateless7_streaming/streaming-ncnn-decode.py", line 109, in __init__
>     self.init_encoder(args)
>   File "pruned_transducer_stateless7_streaming/streaming-ncnn-decode.py", line 210, in init_encoder
>     encoder_net.load_model(encoder_model)
>   File "/home/icefall/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/ncnn_custom_layer.py", line 223, in load_model
>     bias = md.load(self.num_channels, self.upsample, 0)
> TypeError: load(): incompatible function arguments. The following argument types are supported:
>     1. (self: ncnn.ncnn.ModelBinFromDataReader, w: int, type: int) -> ncnn::Mat
> ```

I also tried to use the previous icefall to export model to ncnn, but it still came out of the following error:

```
layer PoolingModuleNoProj not exists or registered
Segmentation fault
```

**Comment by csukuangfj** [comment]
Could you please show the complete commands?

**Comment by PPGGG** [comment]
> Could you please show the complete commands?

The export one is 

`python /home/icefall/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/export-for-ncnn-zh.py --lang-dir /home/icefall/egs/aidatatang/ASR/data/lang_char --exp-dir /home/icefall/egs/aidatatang/ASR/pruned_transducer_stateless7_streaming/exp-14M --use-averaged-model True --iter 66000 --avg 5 --decode-chunk-len 32 --num-encoder-layers "2,3,2,2,3" --feedforward-dims "320,320,640,640,320" --nhead "4,4,4,4,4" --encoder-dims "160,160,160,160,160" --attention-dims "96,96,96,96,96" --encoder-unmasked-dims "128,128,128,128,128" --decoder-dim 320 --joiner-dim 320`

Then i ran the following:
```
pnnx encoder_jit_trace-pnnx.pt
pnnx decoder_jit_trace-pnnx.pt
pnnx joiner_jit_trace-pnnx.pt
```

Finally, i ran the following command to test the exported model.

`python  /home/icefall/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/streaming-ncnn-decode.py --tokens /home/icefall/egs/aidatatang_200zh/ASR/data/lang_char/tokens.txt --encoder-param-filename /home/icefall/egs/aidatatang_200zh/ASR/pruned_transducer_stateless7_streaming/exp-14M/encoder_jit_trace-pnnx.ncnn.param --encoder-bin-filename /home/icefall/egs/aidatatang_200zh/ASR/pruned_transducer_stateless7_streaming/exp-14M/encoder_jit_trace-pnnx.ncnn.bin --decoder-param-filename /home/icefall/egs/aidatatang_200zh/ASR/pruned_transducer_stateless7_streaming/exp-14M/decoder_jit_trace-pnnx.ncnn.param --decoder-bin-filename /home/icefall/egs/aidatatang_200zh/ASR/pruned_transducer_stateless7_streaming/exp-14M/decoder_jit_trace-pnnx.ncnn.bin --joiner-param-filename /home/icefall/egs/aidatatang_200zh/ASR/pruned_transducer_stateless7_streaming/exp-14M/joiner_jit_trace-pnnx.ncnn.param --joiner-bin-filename /home/icefall/egs/aidatatang_200zh/ASR/pruned_transducer_stateless7_streaming/exp-14M/joiner_jit_trace-pnnx.ncnn.bin /home/data/aishell/data_aishell/wav/test/S0764/BAC009S0764W0122.wav`

**Comment by PPGGG** [comment]
@csukuangfj Do i need to use the latest icefall code to re-train my model, so that the exported model can be used in sherpa ncnn ?

**Comment by PPGGG** [comment]
@csukuangfj I just followed the document https://icefall.readthedocs.io/en/latest/model-export/export-ncnn-zipformer.html, trying to decode the audio using the exported model, still get the same error:

```
python pruned_transducer_stateless7_streaming/streaming-ncnn-decode.py \
>   --tokens ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/data/lang_bpe_500/tokens.txt \
>   --encoder-param-filename ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/encoder_jit_trace-pnnx.ncnn.param \
>   --encoder-bin-filename ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/encoder_jit_trace-pnnx.ncnn.bin \
>   --decoder-param-filename ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/decoder_jit_trace-pnnx.ncnn.param \
>   --decoder-bin-filename ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/decoder_jit_trace-pnnx.ncnn.bin \
>   --joiner-param-filename ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/joiner_jit_trace-pnnx.ncnn.param \
>   --joiner-bin-filename ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/joiner_jit_trace-pnnx.ncnn.bin \
>   ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/test_wavs/1089-134686-0001.wav
2023-05-25 22:48:47,713 INFO [streaming-ncnn-decode.py:376] {'tokens': './icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/data/lang_bpe_500/tokens.txt', 'encoder_param_filename': './icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/encoder_jit_trace-pnnx.ncnn.param', 'encoder_bin_filename': './icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/encoder_jit_trace-pnnx.ncnn.bin', 'decoder_param_filename': './icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/decoder_jit_trace-pnnx.ncnn.param', 'decoder_bin_filename': './icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/decoder_jit_trace-pnnx.ncnn.bin', 'joiner_param_filename': './icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/joiner_jit_trace-pnnx.ncnn.param', 'joiner_bin_filename': './icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/joiner_jit_trace-pnnx.ncnn.bin', 'sound_filename': './icefall-asr-liTraceback (most recent call last):ess7-streaming-2022-12-29/test_wavs/1089-134686-0001.wav'}
  File "pruned_transducer_stateless7_streaming/streaming-ncnn-decode.py", line 446, in <module>
    main()
  File "pruned_transducer_stateless7_streaming/streaming-ncnn-decode.py", line 378, in main
    model = Model(args)
  File "pruned_transducer_stateless7_streaming/streaming-ncnn-decode.py", line 109, in __init__
    self.init_encoder(args)
  File "pruned_transducer_stateless7_streaming/streaming-ncnn-decode.py", line 210, in init_encoder
    encoder_net.load_model(encoder_model)
  File "/home/icefall/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/ncnn_custom_layer.py", line 223, in load_model
    bias = md.load(self.num_channels, self.upsample, 0)
TypeError: load(): incompatible function arguments. The following argument types are supported:
    1. (self: ncnn.ncnn.ModelBinFromDataReader, w: int, type: int) -> ncnn::Mat

Invoked with: <ncnn.ncnn.ModelBinFromDataReader object at 0x7efe9d4fb470>, 384, 2, 0
```

**Comment by csukuangfj** [comment]
> @csukuangfj I just git clone the latest icefall code and followed the document https://icefall.readthedocs.io/en/latest/model-export/export-ncnn-zipformer.html, trying to decode the audio using the exported model, still get the same error:
> 
> 
> 
> ```
> 
> python pruned_transducer_stateless7_streaming/streaming-ncnn-decode.py \
> 
> >   --tokens ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/data/lang_bpe_500/tokens.txt \
> 
> >   --encoder-param-filename ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/encoder_jit_trace-pnnx.ncnn.param \
> 
> >   --encoder-bin-filename ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/encoder_jit_trace-pnnx.ncnn.bin \
> 
> >   --decoder-param-filename ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/decoder_jit_trace-pnnx.ncnn.param \
> 
> >   --decoder-bin-filename ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/decoder_jit_trace-pnnx.ncnn.bin \
> 
> >   --joiner-param-filename ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/joiner_jit_trace-pnnx.ncnn.param \
> 
> >   --joiner-bin-filename ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/joiner_jit_trace-pnnx.ncnn.bin \
> 
> >   ./icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/test_wavs/1089-134686-0001.wav
> 
> 2023-05-25 22:48:47,713 INFO [streaming-ncnn-decode.py:376] {'tokens': './icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/data/lang_bpe_500/tokens.txt', 'encoder_param_filename': './icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/encoder_jit_trace-pnnx.ncnn.param', 'encoder_bin_filename': './icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/encoder_jit_trace-pnnx.ncnn.bin', 'decoder_param_filename': './icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/decoder_jit_trace-pnnx.ncnn.param', 'decoder_bin_filename': './icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/decoder_jit_trace-pnnx.ncnn.bin', 'joiner_param_filename': './icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/joiner_jit_trace-pnnx.ncnn.param', 'joiner_bin_filename': './icefall-asr-librispeech-pruned-transducer-stateless7-streaming-2022-12-29/exp/joiner_jit_trace-pnnx.ncnn.bin', 'sound_filename': './icefall-asr-liTraceback (most recent call last):ess7-streaming-2022-12-29/test_wavs/1089-134686-0001.wav'}
> 
>   File "pruned_transducer_stateless7_streaming/streaming-ncnn-decode.py", line 446, in <module>
> 
>     main()
> 
>   File "pruned_transducer_stateless7_streaming/streaming-ncnn-decode.py", line 378, in main
> 
>     model = Model(args)
> 
>   File "pruned_transducer_stateless7_streaming/streaming-ncnn-decode.py", line 109, in __init__
> 
>     self.init_encoder(args)
> 
>   File "pruned_transducer_stateless7_streaming/streaming-ncnn-decode.py", line 210, in init_encoder
> 
>     encoder_net.load_model(encoder_model)
> 
>   File "/home/icefall/egs/librispeech/ASR/pruned_transducer_stateless7_streaming/ncnn_custom_layer.py", line 223, in load_model
> 
>     bias = md.load(self.num_channels, self.upsample, 0)
> 
> TypeError: load(): incompatible function arguments. The following argument types are supported:
> 
>     1. (self: ncnn.ncnn.ModelBinFromDataReader, w: int, type: int) -> ncnn::Mat
> 
> 
> 
> Invoked with: <ncnn.ncnn.ModelBinFromDataReader object at 0x7efe9d4fb470>, 384, 2, 0
> 
> ```

Please install my fork of ncnn. You can find the instructions in the doc. Remember to install the latest commit.
