### ISSUE TITLE
Build fails with libssl missing

### ISSUE THREAD

**Issue by nshmyrev** [k2-fsa/sherpa-ncnn#52]
```
shmyrev@kappa ~ $ pip3 install sherpa-ncnn 
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting sherpa-ncnn
  Downloading sherpa-ncnn-1.1.tar.gz (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.8/41.8 kB 31.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in ./local/lib/python3.7/site-packages (from sherpa-ncnn) (1.21.6)
Building wheels for collected packages: sherpa-ncnn
  Building wheel for sherpa-ncnn (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [69 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.7
      creating build/lib.linux-x86_64-3.7/sherpa_ncnn
      copying sherpa-ncnn/python/sherpa_ncnn/__init__.py -> build/lib.linux-x86_64-3.7/sherpa_ncnn
      copying sherpa-ncnn/python/sherpa_ncnn/recognizer.py -> build/lib.linux-x86_64-3.7/sherpa_ncnn
      running build_ext
      Setting PYTHON_EXECUTABLE to /home/shmyrev/local/bin/python3
      for fast compilation, run:
      export SHERPA_NCNN_MAKE_ARGS="-j"; python setup.py install
      Setting make_args to "-j4"
      build command is:
      
                      cd build/temp.linux-x86_64-3.7
      
                      cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=/home/shmyrev/local/bin/python3 -DCMAKE_INSTALL_PREFIX=/tmp/pip-install-utf4rf_x/sherpa-ncnn_4b5f7058fd5845ee9d77aba1bca97514/build/lib.linux-x86_64-3.7/sherpa_ncnn  -DBUILD_SHARED_LIBS=ON  -DSHERPA_NCNN_ENABLE_PYTHON=ON  -DSHERPA_NCNN_ENABLE_PORTAUDIO=OFF  /tmp/pip-install-utf4rf_x/sherpa-ncnn_4b5f7058fd5845ee9d77aba1bca97514
      
                      make -j4 install/strip
      
      cmake: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
      make: *** No rule to make target 'install/strip'.  Stop.
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-utf4rf_x/sherpa-ncnn_4b5f7058fd5845ee9d77aba1bca97514/setup.py", line 64, in <module>
          license="Apache licensed, as found in the LICENSE file",
        File "/home/shmyrev/local/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/home/shmyrev/local/lib/python3.7/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/home/shmyrev/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/home/shmyrev/local/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/shmyrev/local/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/home/shmyrev/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/shmyrev/local/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/shmyrev/local/lib/python3.7/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/home/shmyrev/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/shmyrev/local/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/shmyrev/local/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/home/shmyrev/local/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
          _build_ext.build_ext.run(self)
        File "/home/shmyrev/local/lib/python3.7/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/home/shmyrev/local/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
          _build_ext.build_ext.build_extensions(self)
        File "/home/shmyrev/local/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
          self._build_extensions_serial()
        File "/home/shmyrev/local/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-install-utf4rf_x/sherpa-ncnn_4b5f7058fd5845ee9d77aba1bca97514/cmake/cmake_extension.py", line 119, in build_extension
          "\nBuild sherpa-ncnn failed. Please check the error message.\n"
      Exception:
      Build sherpa-ncnn failed. Please check the error message.
      You can ask for help by creating an issue on GitHub.
      
      Click:
          https://github.com/k2-fsa/sherpa-ncnn/issues/new
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for sherpa-ncnn
  Running setup.py clean for sherpa-ncnn
Failed to build sherpa-ncnn
Installing collected packages: sherpa-ncnn
  Running setup.py install for sherpa-ncnn ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for sherpa-ncnn did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      running install
      /home/shmyrev/local/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.7
      creating build/lib.linux-x86_64-3.7/sherpa_ncnn
      copying sherpa-ncnn/python/sherpa_ncnn/__init__.py -> build/lib.linux-x86_64-3.7/sherpa_ncnn
      copying sherpa-ncnn/python/sherpa_ncnn/recognizer.py -> build/lib.linux-x86_64-3.7/sherpa_ncnn
      running build_ext
      Setting PYTHON_EXECUTABLE to /home/shmyrev/local/bin/python3
      for fast compilation, run:
      export SHERPA_NCNN_MAKE_ARGS="-j"; python setup.py install
      Setting make_args to "-j4"
      build command is:
      
                      cd build/temp.linux-x86_64-3.7
      
                      cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=/home/shmyrev/local/bin/python3 -DCMAKE_INSTALL_PREFIX=/tmp/pip-install-utf4rf_x/sherpa-ncnn_4b5f7058fd5845ee9d77aba1bca97514/build/lib.linux-x86_64-3.7/sherpa_ncnn  -DBUILD_SHARED_LIBS=ON  -DSHERPA_NCNN_ENABLE_PYTHON=ON  -DSHERPA_NCNN_ENABLE_PORTAUDIO=OFF  /tmp/pip-install-utf4rf_x/sherpa-ncnn_4b5f7058fd5845ee9d77aba1bca97514
      
                      make -j4 install/strip
      
      cmake: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
      make: *** No rule to make target 'install/strip'.  Stop.
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-utf4rf_x/sherpa-ncnn_4b5f7058fd5845ee9d77aba1bca97514/setup.py", line 64, in <module>
          license="Apache licensed, as found in the LICENSE file",
        File "/home/shmyrev/local/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/home/shmyrev/local/lib/python3.7/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/home/shmyrev/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/home/shmyrev/local/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/shmyrev/local/lib/python3.7/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/home/shmyrev/local/lib/python3.7/distutils/command/install.py", line 545, in run
          self.run_command('build')
        File "/home/shmyrev/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/shmyrev/local/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/shmyrev/local/lib/python3.7/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/home/shmyrev/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/shmyrev/local/lib/python3.7/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/shmyrev/local/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/home/shmyrev/local/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
          _build_ext.build_ext.run(self)
        File "/home/shmyrev/local/lib/python3.7/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/home/shmyrev/local/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
          _build_ext.build_ext.build_extensions(self)
        File "/home/shmyrev/local/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
          self._build_extensions_serial()
        File "/home/shmyrev/local/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-install-utf4rf_x/sherpa-ncnn_4b5f7058fd5845ee9d77aba1bca97514/cmake/cmake_extension.py", line 119, in build_extension
          "\nBuild sherpa-ncnn failed. Please check the error message.\n"
      Exception:
      Build sherpa-ncnn failed. Please check the error message.
      You can ask for help by creating an issue on GitHub.
      
      Click:
          https://github.com/k2-fsa/sherpa-ncnn/issues/new
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> sherpa-ncnn

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
WARNING: There was an error checking the latest version of pip.
shmyrev@kappa ~ $ 

```

**Comment by nshmyrev** [comment]
Nevermind, cmake issue
